Feature : Pagination
ich-wtag/Todo-App_Vanilla_Js pull request #7
Opened 2024-01-09 11:38 UTC by ich-wtag

Overview

[Task-6: Pagination](https://trello.com/c/lQYnTMjK/8-task-7-pagination)
This PR includes pagination functionality. Initially there is no "Load more" button. When todos is more than 9 "Load More" button will be visible. By clicking it, 6 more tasks will be added. And finally when there is no tasks to show "Show Less " will be shown. And when clicking it, like as first, 9 tasks will be visible along with the "Load More" button.
 
Types of Changes

- [x] If todos are less than or equal to 9, nothing changes.
- [x] If todos are more than 9, there is a “Load More” button at the bottom of the UI.
- [x] The load more button loads 6 more todos each time.
- [x] When all the todos are shown, the “Load More” button disappears and “Show Less” button appears.
- [x] Clicking the “Show Less” Button resets the state back to 9 todos.

[pagination.webm](https://github.com/ich-wtag/Todo-App_Vanilla_Js/assets/153156568/675ba34a-eb1c-4fcf-af7d-7cd1da6b6c55)

2024-01-14 08:14 UTC, hhu-wtag requested changes

2024-01-14 08:14 UTC, hhu-wtag commented on script.js
> +let totalPage = 1;
magic number
A unique value with unexplained meaning or multiple occurrences which could (preferably) be replaced with a named constant.

```suggestion
import { INITIAL_PAGE, PAGE_LOAD_COUNT } from "./const.js"
let currentPage = INITIAL_PAGE;
let totalPage = INITIAL_PAGE;
const pageLoadCount = PAGE_LOAD_COUNT;
```


Do we need the endIndex? 
Can't endIndex be calculated everytime we apply pagination?

```js
const endIndex = currentPage * perPage
const arr = todos.slice(0, endIndex)
```
As slice takes care of the overflow, we don't need to think about it.

2024-01-14 08:14 UTC, hhu-wtag commented on script.js
> +        currentPage < totalPage ? "Load More" : "Show Less";
**Show Less** will be only available when all the items are shown.

2024-01-14 08:14 UTC, hhu-wtag commented on script.js
> +const getPaginatedArray = (toBePaginatedArray) => {
```suggestion
const getPaginatedArray = (todos) => {
```

2024-01-14 08:25 UTC, ich-wtag commented on script.js
> +        currentPage < totalPage ? "Load More" : "Show Less";
bhai currently **Show Less** button only visible when the current page number is equal to the totalPage. That means when all todos are visible only then **Show Less** button will be visible.

2024-01-14 08:34 UTC, ich-wtag commented on script.js
> +let totalPage = 1;
bhai if we want to show same numbers of todos on both first page and after clicking the **Load More** , then we don't need the endIndex. But according to trello we have to show 9 todos at first, while clicking **Load More** another 6 todos will be added in the dom. So in this case I have handled that task differently.

2024-01-14 08:51 UTC, hhu-wtag commented on script.js
> +let totalPage = 1;
Got it. I think let's not make it complicated. Let's initially show 9 or `PER_PAGE_TODO` count and on each click of Load More button, we'll show `PER_PAGE_TODO` more.

2024-01-14 10:00 UTC, hhu-wtag commented on script.js
> +        currentPage < totalPage ? "Load More" : "Show Less";
It's okay in that case.

2024-01-17 05:08 UTC, hhu-wtag approved these changes

2024-01-17 06:41 UTC, merged